import "./globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import "./styles/main.scss";
import DarkMode from "./clientComponent/common/DarkMode";
import Footer from "./clientComponent/main/Footer";
import Header from "./clientComponent/main/header/Header";
import localFont from "next/font/local";
import { Providers } from "./globalRedux/provider";
import NavigateMobile from './clientComponent/utils/NavigateMobile';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = localFont({
  src: [
    {
      path: "../../../public/fonts/Kanit-Black.ttf",
      style: "normal",
      weight: "600",
    },
    {
      path: "../../../public/fonts/Kanit-BlackItalic.ttf",
      style: "italic",
      weight: "300",
    },
    {
      path: "../../../public/fonts/Kanit-Bold.ttf",
      style: "bold",
      weight: "500",
    },
    {
      path: "../../../public/fonts/Kanit-ExtraLight.ttf",
      style: "normal",
      weight: "100",
    },
  ],
  variable: "--font-kanit",
});

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      dir="ltr"
      className={`${kanit.variable} font-sans font-thin`}
    >
      <body className="bg-myCustomBgBody dark:bg-gray-700  h-screen p-0 m-0 overflow-x-hidden  ">
        <Providers>
          {" "}
          <Header />
          <div className=" px-3 md:mx-md-0 sm:max-w-2xl md:max-w-custom  mx-auto">
            {children}
          </div>
          <Footer />
          <div className="hidden md:block">
          <DarkMode />
          </div>
          <NavigateMobile/>
        </Providers>
      </body>
    </html>
  );
}
