// process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
import ServerParent from "./ServerParent";
export const metadata = {
  title: "text meta tags ",
  description: "Generated by create next app",
};


const Home =  () => {

  return (
    <>
      <title>Home Page</title>
      <ServerParent />
    </>
  );
};
export default Home;
